<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[testA]]>
    </line>
    <line>
      <![CDATA[testA Status:2]]>
    </line>
    <line>
      <![CDATA[closeApp]]>
    </line>
    <line>
      <![CDATA[testB]]>
    </line>
    <line>
      <![CDATA[testB Status:1]]>
    </line>
    <line>
      <![CDATA[closeApp]]>
    </line>
    <line>
      <![CDATA[Data : UserName]]>
    </line>
    <line>
      <![CDATA[Row : 1]]>
    </line>
    <line>
      <![CDATA[Test: testA is Failed & Photo is: ./photo/Fri Sep 28 23_08_43 IST 2018.png]]>
    </line>
    <line>
      <![CDATA[TestDemo2]]>
    </line>
    <line>
      <![CDATA[Test: testDemo2 is PASSED]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="71282" started-at="2018-09-28T17:38:06Z" finished-at="2018-09-28T17:39:18Z">
    <groups>
    </groups>
    <test name="me" duration-ms="71282" started-at="2018-09-28T17:38:06Z" finished-at="2018-09-28T17:39:18Z">
      <class name="script.DemoA">
        <test-method status="FAIL" signature="testA()[pri:0, instance:script.DemoA@57fffcd7]" name="testA" duration-ms="36" started-at="2018-09-28T17:38:07Z" finished-at="2018-09-28T17:38:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.DemoA.testA(DemoA.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[testA]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.DemoA@57fffcd7]" name="closeApp" is-config="true" duration-ms="15" started-at="2018-09-28T17:38:07Z" finished-at="2018-09-28T17:38:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=DemoA.testA()[pri:0, instance:script.DemoA@57fffcd7] output=testA]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testA Status:2]]>
            </line>
            <line>
              <![CDATA[closeApp]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.DemoA@57fffcd7]" name="closeApp" is-config="true" duration-ms="16" started-at="2018-09-28T17:38:07Z" finished-at="2018-09-28T17:38:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testB status=SUCCESS method=DemoA.testB()[pri:0, instance:script.DemoA@57fffcd7] output=testB]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testB Status:1]]>
            </line>
            <line>
              <![CDATA[closeApp]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method status="PASS" signature="testB()[pri:0, instance:script.DemoA@57fffcd7]" name="testB" duration-ms="0" started-at="2018-09-28T17:38:07Z" finished-at="2018-09-28T17:38:07Z">
          <reporter-output>
            <line>
              <![CDATA[testB]]>
            </line>
          </reporter-output>
        </test-method> <!-- testB -->
      </class> <!-- script.DemoA -->
      <class name="script.TestDemo">
        <test-method status="PASS" signature="openApp(java.lang.String, java.lang.String)[pri:0, instance:script.TestDemo@31ef45e3]" name="openApp" is-config="true" duration-ms="35469" started-at="2018-09-28T17:38:07Z" finished-at="2018-09-28T17:38:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="testA()[pri:0, instance:script.TestDemo@31ef45e3]" name="testA" duration-ms="772" started-at="2018-09-28T17:38:42Z" finished-at="2018-09-28T17:38:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.TestDemo.testA(TestDemo.java:20)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Data : UserName]]>
            </line>
            <line>
              <![CDATA[Row : 1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.TestDemo@31ef45e3]" name="closeApp" is-config="true" duration-ms="1658" started-at="2018-09-28T17:38:43Z" finished-at="2018-09-28T17:38:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=TestDemo.testA()[pri:0, instance:script.TestDemo@31ef45e3] output=Data : UserName]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test: testA is Failed & Photo is: ./photo/Fri Sep 28 23_08_43 IST 2018.png]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.TestDemo -->
      <class name="script.TestDemo2">
        <test-method status="PASS" signature="openApp(java.lang.String, java.lang.String)[pri:0, instance:script.TestDemo2@598067a5]" name="openApp" is-config="true" duration-ms="32372" started-at="2018-09-28T17:38:44Z" finished-at="2018-09-28T17:39:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="PASS" signature="testDemo2()[pri:0, instance:script.TestDemo2@598067a5]" name="testDemo2" duration-ms="6" started-at="2018-09-28T17:39:17Z" finished-at="2018-09-28T17:39:17Z">
          <reporter-output>
            <line>
              <![CDATA[TestDemo2]]>
            </line>
          </reporter-output>
        </test-method> <!-- testDemo2 -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.TestDemo2@598067a5]" name="closeApp" is-config="true" duration-ms="874" started-at="2018-09-28T17:39:17Z" finished-at="2018-09-28T17:39:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testDemo2 status=SUCCESS method=TestDemo2.testDemo2()[pri:0, instance:script.TestDemo2@598067a5] output=TestDemo2]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test: testDemo2 is PASSED]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.TestDemo2 -->
    </test> <!-- me -->
  </suite> <!-- Suite -->
</testng-results>
